services:
  - type: web
    name: chatgpt
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    autoDeploy: true
    envVars:
      - key: chatgpt
        sync: false  
      - key: PORT
        value: "10000"
